package com.example.smartairmonitoring.Data.local.entities

import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "air_pollution")
data class AirPollEntity(
    @PrimaryKey val city: String, // Or use an autogenerated ID
    @Embedded val data: AirPollData
)

data class AirPollData(
    val lat: Double,
    val lon: Double,
    val pm25: Double,
    val pm10: Double,
    val no2: Double,
    val no: Double,
    val o3: Double,
    val so2: Double,
    val co: Double,
    val nh3: Double,
    val aqi: Int,
    val dt: String
)


